In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

Collecting faiss-cpu
  Downloading faiss_cpu-1.11.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from faiss-cpu) (2.2.6)
Requirement already satisfied: packaging in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from faiss-cpu) (24.2)
Downloading faiss_cpu-1.11.0-cp312-cp312-win_amd64.whl (15.0 MB)
   ---------------------------------------- 0.0/15.0 MB ? eta -:--:--
   --------- ------------------------------ 3.4/15.0 MB 18.3 MB/s eta 0:00:01
   -------------------- ------------------- 7.6/15.0 MB 18.8 MB/s eta 0:00:01
   ------------------------------ --------- 11.3/15.0 MB 19.0 MB/s eta 0:00:01
   ---------------------------------------  14.9/15.0 MB 18.8 MB/s eta 0:00:01
   ---------------------------------------- 15.0/15.0 MB 17.8 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.11.0
Collecting sentence-transformers
  Downloading sentence_transformers-4.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (4.52.3)
Requirement already satisfied: tqdm in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (2.7.0)
Collecting scikit-learn (from sentence-transformers)
  Downloading scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: scipy in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (0.32.2)
Requirement already satisfied: Pillow in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sentence-transformers) (4.12.2)
Requirement already satisfied: filelock in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.5.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from torch>=1.11.0->sentence-transformers) (78.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.4.26)
Requirement already satisfied: joblib>=1.2.0 in c:\users\kaush\anaconda3\envs\genai\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.1)
Collecting threadpoolctl>=3.1.0 (from scikit-learn->sentence-transformers)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading sentence_transformers-4.1.0-py3-none-any.whl (345 kB)
Downloading scikit_learn-1.6.1-cp312-cp312-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ------------- -------------------------- 3.7/11.1 MB 18.2 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/11.1 MB 16.8 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.1 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 16.1 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scikit-learn, sentence-transformers

   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   ------------- -------------------------- 1/3 [scikit-learn]
   -------------------------- ------------- 2/3 [sentence-transformers]
   -------------------------- ------------- 2/3 [sentence-transformers]
   -------------------------- ------------- 2/3 [sentence-transformers]
   -------------------------- ------------- 2/3 [sentence-transformers]
   -------------------------- ------------- 2/3 [sentence-transformers]
   ---------------------------------------- 3/3 [sentence-transformers]

Successfully installed scikit-learn-1.6.1 sentence-transformers-4.1.0 threadpoolctl-3.6.0

In [2]:
import pandas as pd

pd.set_option("display.max_colwidth", 100)

In [3]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [4]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [8]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vector = encoder.encode(df.text)

C:\Users\kaush\anaconda3\envs\genai\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\kaush\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [9]:
vector.shape

(8, 768)

In [10]:
vector

array([[-0.00247389,  0.03626734, -0.05290461, ..., -0.09152357,
        -0.03969997, -0.04330492],
       [-0.03357262,  0.0098052 , -0.03250131, ..., -0.05165471,
         0.02245888, -0.0315618 ],
       [-0.01865329, -0.0405131 , -0.01235393, ...,  0.00610591,
        -0.07179642,  0.02773851],
       ...,
       [-0.00066455,  0.0425213 , -0.05645505, ...,  0.01315467,
        -0.03183567, -0.04357664],
       [-0.03317151,  0.03252457, -0.0248484 , ...,  0.01174416,
         0.05747122,  0.00571025],
       [-0.00166394,  0.00413823, -0.04597079, ...,  0.02008532,
         0.05656243, -0.00161595]], shape=(8, 768), dtype=float32)

In [11]:
dim = vector.shape[1]
dim

768

In [12]:
import faiss
index = faiss.IndexFlatL2(dim)

In [14]:
index.add(vector)

In [25]:
search_quary= "i want to go to concert"

vec = encoder.encode(search_quary)
vec.shape

(768,)

In [26]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [27]:
distance, i =index.search(svec, k=2)

In [28]:
i

array([[4, 5]])

In [29]:
df.loc[i[0]]

                                                              text category
4                               The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mumbai this october    Event